import { DocumentationQualityIssue } from './quality-types';

export interface QualityRuleDef {
  id: string;
  category: DocumentationQualityIssue['category'];
  severity: DocumentationQualityIssue['severity'];
  scoreImpact: number;
  title: string;
  description: string;
  recommendation: string;
  action: DocumentationQualityIssue['action'];
}

export const QUALITY_RULES: Record<string, QualityRuleDef> = {
  DOC001: {
    id: 'DOC001',
    category: 'clarity',
    severity: 'critical',
    scoreImpact: 20,
    title: 'Missing project title',
    description: 'The documentation is missing a primary title (H1 heading).',
    recommendation: 'Add a clear H1 heading (e.g., `# Project Name`) at the very top of your README.',
    action: 'add-section',
  },
  DOC002: {
    id: 'DOC002',
    category: 'clarity',
    severity: 'important',
    scoreImpact: 10,
    title: 'Project purpose is unclear',
    description: 'The introduction section is missing or too short to explain what the project is and what problem it solves.',
    recommendation: 'Write a brief 2-3 sentence overview describing the purpose, goals, and key features of the project.',
    action: 'improve-section',
  },
  DOC003: {
    id: 'DOC003',
    category: 'setup',
    severity: 'critical',
    scoreImpact: 20,
    title: 'Installation instructions are missing',
    description: 'There is no documented section on how to install or setup this repository.',
    recommendation: 'Add an "Installation" section detailing the step-by-step commands to get the project set up locally.',
    action: 'add-section',
  },
  DOC004: {
    id: 'DOC004',
    category: 'setup',
    severity: 'important',
    scoreImpact: 10,
    title: 'Prerequisites are missing',
    description: 'The documentation does not list required tools, runtimes (like Node.js, Docker), or minimum versions required.',
    recommendation: 'Specify the runtimes and system tools (e.g., Node.js >= 18) under a "Prerequisites" subsection.',
    action: 'improve-section',
  },
  DOC005: {
    id: 'DOC005',
    category: 'usage',
    severity: 'important',
    scoreImpact: 15,
    title: 'Usage examples are missing',
    description: 'No code snippets or basic execution instructions are provided to help users run or interact with the project.',
    recommendation: 'Add a "Usage" section with practical command examples or code snippets showcasing how to run the project.',
    action: 'add-section',
  },
  DOC006: {
    id: 'DOC006',
    category: 'setup',
    severity: 'important',
    scoreImpact: 10,
    title: 'Environment configuration is undocumented',
    description: 'The repository contains configuration templates (like .env.example) but has no explanation of how to configure them.',
    recommendation: 'Add an "Environment Configuration" section listing the required environment variables and explaining their purpose.',
    action: 'add-section',
  },
  DOC007: {
    id: 'DOC007',
    category: 'usage',
    severity: 'suggestion',
    scoreImpact: 5,
    title: 'Available scripts are undocumented',
    description: 'The package has defined build or run scripts in package.json that are not documented in the README.',
    recommendation: 'Add a table or list detailing what commands like `npm run dev`, `npm run build`, and `npm test` do.',
    action: 'improve-section',
  },
  DOC008: {
    id: 'DOC008',
    category: 'usage',
    severity: 'suggestion',
    scoreImpact: 5,
    title: 'Testing instructions are missing',
    description: 'Test suites are present in the repository, but there are no instructions on how to run them.',
    recommendation: 'Add a "Testing" section showing how to execute the test suite (e.g., `npm run test`).',
    action: 'add-section',
  },
  DOC009: {
    id: 'DOC009',
    category: 'repository-coverage',
    severity: 'important',
    scoreImpact: 10,
    title: 'API usage is undocumented',
    description: 'The repository exposes API endpoints or is a server-side app, but does not document how to call them.',
    recommendation: 'Include an "API Documentation" section with endpoints, query parameters, request bodies, and sample responses.',
    action: 'add-section',
  },
  DOC010: {
    id: 'DOC010',
    category: 'repository-coverage',
    severity: 'important',
    scoreImpact: 10,
    title: 'Docker support is undocumented',
    description: 'The project contains Docker configuration (Dockerfile/docker-compose.yml) but has no instructions on running via Docker.',
    recommendation: 'Add a "Docker Setup" section explaining how to build images and spin up containers using docker-compose.',
    action: 'add-section',
  },
  DOC011: {
    id: 'DOC011',
    category: 'structure',
    severity: 'important',
    scoreImpact: 5,
    title: 'Duplicate heading detected',
    description: 'Multiple sections share the exact same heading title, which can cause navigation issues.',
    recommendation: 'Rename duplicate headings to be unique and descriptive (e.g., "Client Setup" and "Server Setup" instead of two "Setup" headings).',
    action: 'fix-structure',
  },
  DOC012: {
    id: 'DOC012',
    category: 'structure',
    severity: 'suggestion',
    scoreImpact: 5,
    title: 'Heading hierarchy is inconsistent',
    description: 'Heading level jumps were detected (e.g., jumping from H1 directly to H3, skipping H2).',
    recommendation: 'Adjust heading levels to follow a logical nested order (H1 -> H2 -> H3).',
    action: 'fix-structure',
  },
  DOC013: {
    id: 'DOC013',
    category: 'structure',
    severity: 'important',
    scoreImpact: 10,
    title: 'Empty documentation section',
    description: 'A section heading was found with no content following it.',
    recommendation: 'Add content to this section, or remove the empty heading.',
    action: 'improve-section',
  },
  DOC014: {
    id: 'DOC014',
    category: 'maintenance',
    severity: 'critical',
    scoreImpact: 15,
    title: 'Placeholder content detected',
    description: 'Documentation contains unresolved placeholders (e.g., TODO, TBD, "Your project description here", or placeholder api keys).',
    recommendation: 'Replace placeholder values and template indicators with real, accurate information.',
    action: 'improve-section',
  },
  DOC015: {
    id: 'DOC015',
    category: 'structure',
    severity: 'important',
    scoreImpact: 10,
    title: 'README is too short for repository complexity',
    description: 'The overall volume of documentation is very low compared to the size and variety of files in the repository.',
    recommendation: 'Expand the README content, detailing architectural decisions, features, and setup instructions in depth.',
    action: 'improve-section',
  },
  DOC016: {
    id: 'DOC016',
    category: 'repository-coverage',
    severity: 'important',
    scoreImpact: 10,
    title: 'Important repository feature is not documented',
    description: 'Major technologies or files detected in the repository are completely omitted from the documentation.',
    recommendation: 'Mention key features and integrations (e.g., database, styling library, caching) in the README introduction or features list.',
    action: 'improve-section',
  },
  DOC017: {
    id: 'DOC017',
    category: 'maintenance',
    severity: 'suggestion',
    scoreImpact: 5,
    title: 'Configuration variable is not explained',
    description: 'A key configuration or environment variable is mentioned in the repository setup but has no explanation.',
    recommendation: 'Provide short explanations for each configuration key required by the application.',
    action: 'improve-section',
  },
  DOC018: {
    id: 'DOC018',
    category: 'maintenance',
    severity: 'suggestion',
    scoreImpact: 5,
    title: 'Contribution guidance is missing',
    description: 'The repository is classified as open source or collaborative, but does not provide details on how to contribute.',
    recommendation: 'Add a "Contributing" section detailing steps for bug reports, PR submissions, and coding guidelines.',
    action: 'add-section',
  },
  DOC019: {
    id: 'DOC019',
    category: 'maintenance',
    severity: 'suggestion',
    scoreImpact: 5,
    title: 'License information is missing',
    description: 'No license is documented in the README, and the repository does not contain a LICENSE file.',
    recommendation: 'Add a "License" section specifying the license type (e.g., MIT, Apache 2.0).',
    action: 'add-section',
  },
  DOC020: {
    id: 'DOC020',
    category: 'usage',
    severity: 'important',
    scoreImpact: 10,
    title: 'Code examples are missing where they would improve usability',
    description: 'The codebase contains complex structures or is a reusable library, but does not show code blocks representing use-cases.',
    recommendation: 'Provide clear, copy-pasteable code examples showing how to import, call, or configure the project components.',
    action: 'improve-section',
  },
};
