import { describe, it, expect } from 'vitest';
import { MarkdownValidator } from './markdown-validator';

describe('MarkdownValidator', () => {
  it('should inject a title if missing', () => {
    const raw = `This is just some text that is longer than fifty characters to pass the validation check.\n\n## Subheading`;
    const clean = MarkdownValidator.validate(raw);
    expect(clean.startsWith('# Generated Documentation')).toBe(true);
  });

  it('should not inject a title if present', () => {
    const raw = `# My Real Title\n\nThis is just some text that is longer than fifty characters to pass the validation check.\n\n## Subheading`;
    const clean = MarkdownValidator.validate(raw);
    expect(clean.startsWith('# My Real Title')).toBe(true);
    expect(clean.includes('# Generated Documentation')).toBe(false);
  });

  it('should close unclosed code blocks', () => {
    const raw = `# Title\n\nThis is just some text that is longer than fifty characters to pass the validation check.\n\n\`\`\`javascript\nconst a = 1;`;
    const clean = MarkdownValidator.validate(raw);
    // Should have an even number of code block ticks now
    const matches = clean.match(/```/g) || [];
    expect(matches.length % 2).toBe(0);
  });

  it('should remove AI generated disclaimers', () => {
    const raw = `# Title\n\nThis README was generated by AI based on repository evidence.\n\nMore text.`;
    const clean = MarkdownValidator.validate(raw);
    expect(clean.includes('This README was generated')).toBe(false);
  });

  it('should throw on empty or suspiciously short content', () => {
    expect(() => MarkdownValidator.validate('')).toThrow();
    expect(() => MarkdownValidator.validate('Too short')).toThrow();
  });
});
